- rule: "rpc.enable?"
  description: "Must have an RPC enabled"
  suggestions:
    - SET:
        var: "rpc.enable"
        to-value: true
- rule: "advanced.blockfilters.blockfilterindex?"
  description: "Must have block filter index enabled for Run The Numbers to work"
  suggestions:
    - SET:
        var: "advanced.blockfilters.blockfilterindex"
        to-value: true
- rule: "!(#rpc.advanced.threads < 4)"
  description: "Must be >= 4"
  suggestions:
    - SET:
        var: "rpc.advanced.threads"
        to-value: 4
- rule: "!(#rpc.advanced.workqueue < 128)"
  description: "Must be >= 128"
  suggestions:
    - SET:
        var: "rpc.advanced.workqueue"
        to-value: 128
